### ISSUE TITLE
Lost sticky notes

### ISSUE THREAD

**Issue by drjwbaker** [LibraryCarpentry/week-one-library-carpentry#6]
It isn't a big deal, but I seem to have misplaced the sticky notes that people wrote names/phrases on that they wanted to know more about. @davanstrien: you left at the same time as me, any recollection of what I did with them?

**Comment by davanstrien** [comment]
@drjwbaker I remember collecting them but not where they went afterwards. I can have a quick rummage through my bag but I'm pretty sure I didn't take them by mistake.

**Comment by drjwbaker** [comment]
@davanstrien Ta!
